package export

import (
	"fmt"
	"strings"

	"github.com/yudopr11/subforge/internal/domain"
)

const assHeaderTemplate = `[Script Info]
; Script generated by SubForge (https://github.com/yudopr11/subforge)
Title: %s
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: None
PlayResX: 1920
PlayResY: 1080

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,52,&H00FFFFFF,&H000000FF,&H00000000,&H80000000,-1,0,0,0,100,100,0,0,1,3,2,2,40,40,40,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
`

func GenerateASS(segments []domain.Segment, title string) string {
	var sb strings.Builder
	sb.WriteString(fmt.Sprintf(assHeaderTemplate, title))

	for _, seg := range segments {
		start := domain.FormatASSTime(seg.Start)
		end := domain.FormatASSTime(seg.End)
		speaker := seg.Speaker
		text := strings.TrimSpace(seg.Source)
		// Escape newlines for ASS
		text = strings.ReplaceAll(text, "\n", "\\N")
		sb.WriteString(fmt.Sprintf("Dialogue: 0,%s,%s,Default,%s,0,0,0,,%s\n", start, end, speaker, text))
	}
	return sb.String()
}
